### ISSUE TITLE
[Web] Add location change, doctor change, and instruction management appointment modification page

### ISSUE THREAD

**Issue by sweng270** [ssxsora/VMA-Web-App#20]
[Web Application - Appointment Change]

When changing/rescheduling a patient's appointment, the user should also be able to change the location of the procedure (on the same page).

**Comment by mkcrto** [comment]
Added a Location field to the Appointment Djang-admin page so the user can change the location while editing the appointment

**Comment by mkcrto** [comment]
In order to add the instruction management functionality, we will need to create an entirely separate page (i.e. not use the admin site).  This is because the Django admin site is intended to handle single references, e.g. appointment references doctor so you can easily grab the associated doctor record. However, the relationship between appointment and instructionsperpatient is a one to many, which the Django admin site does not support.  I tried running a query on the database then creating a set of custom, "non-model" fields, but the framework simply ignores those fields and they do not show up on the edit page.

**Comment by cquinn5** [comment]
INSTRUCTION MANAGEMENT:
requires instruction, medinstruction, insattribute, medproc

INSTRUCTIONSPERPATIENT VIEWS:
requires instructionsperpatient, appointment, medinstruction ??

**Comment by ssxsora** [comment]
completed ins per patient and ins management views
