### ISSUE TITLE
Add logic to correctly populate tables after a preproc form is filled

### ISSUE THREAD

**Issue by ssxsora** [ssxsora/VMA-Web-App#43]
Our logic has not been updated to reflect the DB changes in early April. It needs to be changed to populate the following tables:

- patient
- patientattribute
- appointment
- instructionsperpatient

**Comment by cquinn5** [comment]
patient and appointment get created already, they need to be leveraged to get patientattribute and instructionsperpatient

patientattribute needs:
patientid
insattributeid from insattributeinterface.getinsattributeidbyattributetype(attribute_type) where attribute_type comes from the answer to the question

instructionsperpatient needs:
appointmentid
medinstructionid
instructiondesc derived from medinstruction and related medproc and instruction objects, as well as the time. unit, and day??? this is where I get lost a little bit
remindertime

taking notes here because it's easier than making huge comments in code comments

**Comment by cquinn5** [comment]
I did this successfully, but I didn't really test it extensively
