### ISSUE TITLE
[Web] Change procedure names

### ISSUE THREAD

**Issue by ssxsora** [ssxsora/VMA-Web-App#9]
ENDO to EGD

SIGMO to FLEX SIG

**Comment by sweng270** [comment]
I will make a note to ask the staff at the medical facility on Monday for the list of procedures that they currently do and the shorthand/abbreviation for each.

**Comment by cquinn5** [comment]
@sweng270 , do you have a list of these yet? Either attach here or update CSVs, I think this belongs in high severity because it's something we must deliver to IK

**Comment by sweng270** [comment]
Yes, I have the list of all the procedures that they currently do. I've updated the med_proc.csv file (since it wouldn't let me attach it here). As for the procedure descriptions, I've updated what's there and added in the new ones based off of information that I either got from the office or their website. The only descriptions that I didn't receive information about and wasn't included on their website are the COMBO and BRAVO procedures, but I filled in a short description for those.
